### ISSUE TITLE
Drain：in step 3，the number of internal nodes is depth-2?

### ISSUE THREAD

**Issue by zhanla** [logpai/logparser#43] opened 2019-08-20 02:13 UTC
in paper ,step 3,The number of internal nodes that Drain traverses in this
step is (depth − 2), where depth is the parse tree parameter
restricting the depth of all leaf nodes.
but in code,  the number of internal nodes  is depth -2 -1.
Can you give me an explanation?

**Comment by Wapiti08** [comment] 2019-08-22 10:59
I know all the demo is based on the format of HDFS. How about the Linux system logs?
I used log_format = '<Month> <Date> <Time> <Level> <Component><PID>: <Content>', but i did not get the expected performance in the csv file. I think the problem is between <Component> and <PID>. Could it be possible for you to give me some instructions? Thank you.

**Comment by Wapiti08** [comment] 2019-08-22 11:49
<Month> <Date> <Time> <Level> <Component>\[<PID>\]: <Content>           I have fixed this issue

**Comment by jimzhu** [comment] 2019-08-22 12:16
@Wapiti08  You can check the benchmarks/ folder for the details about running linux logs.

**Comment by Wapiti08** [comment] 2019-08-22 14:02
Thank you so much.

**Comment by Wapiti08** [comment] 2019-08-22 14:31
Sorry to interrupt you again. I have run the code in benchmark. I have a problem about the EventID. They always come out like da153daf,... such stuff, while not E12,... I am not sure where the problem comes from. Could you have a look about that? Really appreciate that.

**Comment by Wapiti08** [comment] 2019-08-22 16:03
Do i need to read the eventID line from templates.csv and rewrite them into Exx? Or do you have any available way in this tool?

**Comment by Wapiti08** [comment] 2019-08-22 16:21
By the way, i also want to know how you compute the group number of linux logs, I found there are 118 clusters in total. But i do not know how you got that.
I used the same dataset and the algorithm DBSCAN to compute it. I got 91 clusters in total. Hope to know about the method you used. Thank you!

**Comment by jimzhu** [comment] 2019-08-23 05:05
> Do i need to read the eventID line from templates.csv and rewrite them into Exx? Or do you have any available way in this tool?

We intentionally use a hash ID as eventID. This facilitates better ID management such as merging two eventIDs or splitting it during postprocessing. Meanwhile, different templates can be quickly merged.

**Comment by jimzhu** [comment] 2019-08-23 05:07
> By the way, i also want to know how you compute the group number of linux logs, I found there are 118 clusters in total. But i do not know how you got that.
> I used the same dataset and the algorithm DBSCAN to compute it. I got 91 clusters in total. Hope to know about the method you used. Thank you!

If you run the logparser, the number of templates is automatically determined. If you refer to the ground truth file, it is manual work.

**Comment by Wapiti08** [comment] 2019-08-23 08:45
> > By the way, i also want to know how you compute the group number of linux logs, I found there are 118 clusters in total. But i do not know how you got that.
> > I used the same dataset and the algorithm DBSCAN to compute it. I got 91 clusters in total. Hope to know about the method you used. Thank you!
> 
> If you run the logparser, the number of templates is automatically determined. If you refer to the ground truth file, it is manual work.

Thanks for you reply. I understood.

**Comment by PinjiaHe** [comment] 2019-08-29 09:15
@zhanla I am not sure which code line(s) you refer to. We implement the traverse of the length node and the traverse of the token nodes (in a loop) separately. So I guess the difference is caused by implementation details. In any case, you could stick with the code, since theoretically it aligns with the idea described in the paper.

**Closed** 2019-08-31 09:19 UTC
